# Generated by Django 2.1.4 on 2019-01-17 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unnamed Event', max_length=200)),
                ('day', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('details', models.CharField(blank=True, max_length=1500, null=True)),
                ('slug', models.SlugField(default=models.CharField(blank=True, default='Unnamed Event', max_length=200), max_length=255)),
                ('address', models.CharField(default='', max_length=250, null=True)),
                ('attendees', models.ManyToManyField(blank=True, default='None', related_name='attendees', to=settings.AUTH_USER_MODEL)),
                ('organisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'events',
            },
        ),
    ]
