# Generated by Django 2.1.4 on 2019-01-17 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Event Group', max_length=200, unique=True)),
                ('details', models.CharField(blank=True, max_length=1500, null=True)),
                ('main_user_group', models.ManyToManyField(blank=True, default='None', related_name='group_user', to=settings.AUTH_USER_MODEL)),
                ('organisor_group', models.ManyToManyField(blank=True, default='None', related_name='group_organisor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='events',
            name='organisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_organisor', to=settings.AUTH_USER_MODEL),
        ),
    ]
