# Generated by Django 2.1.4 on 2019-01-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='slug',
            field=models.SlugField(default=models.CharField(blank=True, default='Unnamed Event', max_length=200), max_length=255),
        ),
    ]
