# Generated by Django 2.1.4 on 2019-01-17 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190117_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventgroups',
            options={'verbose_name_plural': 'events'},
        ),
    ]
