# Generated by Django 2.1.4 on 2019-01-18 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190117_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.EventGroups'),
        ),
    ]
