# Generated by Django 2.1.4 on 2019-03-20 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190320_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.EventGroup'),
        ),
    ]
