# Generated by Django 2.1.4 on 2019-03-20 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20190320_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventgroupold',
            name='main_user_group',
        ),
        migrations.RemoveField(
            model_name='eventgroupold',
            name='organisor_group',
        ),
        migrations.DeleteModel(
            name='EventGroupOld',
        ),
    ]
